#!/bin/bash
disconnect;
psql -U postgres -c "DROP DATABASE IF EXISTS bulletpoint_test";
psql -U postgres -c "CREATE DATABASE bulletpoint_test";
psql -U postgres bulletpoint_test < /var/www/bulletpoint/fixtures/schema.sql;
psql -U postgres bulletpoint_test < /var/www/bulletpoint/Tests/Fixtures/plest.sql;
psql -U postgres bulletpoint_test < /var/www/bulletpoint/Tests/Fixtures/samples.sql;
psql -U postgres bulletpoint_test < /var/www/bulletpoint/Tests/Fixtures/test_utils.sql;

psql -U postgres -c "DROP DATABASE IF EXISTS bulletpoint";
psql -U postgres -c "CREATE DATABASE bulletpoint";
psql -U postgres bulletpoint < /var/www/bulletpoint/fixtures/schema.sql;
psql -U postgres bulletpoint < /var/www/bulletpoint/fixtures/test.sql;