sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  - docker network create bulletpoint
  - docker volume create --name=bulletpoint-postgres

  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose -p bulletpoint up -d --build

before_script:
  - docker exec bulletpoint_php-fpm_1 make composer-install
  - docker exec bulletpoint-postgres test_import
  - docker exec bulletpoint_node_1 yarn

script:
  - docker exec -e "TRAVIS=true" bulletpoint_php-fpm_1 make ci
  - docker exec -e "TRAVIS=true" bulletpoint-postgres make migration-diff
  - docker exec -e "TRAVIS=true" bulletpoint_node_1 yarn run check

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e5a5ec65f236_key -iv $encrypted_e5a5ec65f236_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - mkdir -p ~/.ssh
  - mv id_rsa ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: sh deploy/deploy.sh
  on:
    branch: master

after_failure:
  - docker exec bulletpoint_php-fpm_1 make echo-failed-tests
