language: php

php:
  - 7.0

env:
  - PHP_BIN="php-cgi"

matrix:
    include:
        - php: 7.0
          env: coverage="--coverage ./coverage.xml --coverage-src ./app" PHP_BIN=phpdbg

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE bulletpoint_test;'
  - mysql -u root -e 'CREATE DATABASE pdo_test;'
  - mysql -u root bulletpoint_test < ./tests/bulletpoint_test.sql
  - mysql -u root pdo_test < ./tests/Model/Unit/Storage/pdo_test.sql

script:
  - ./vendor/bin/tester -p $PHP_BIN -o console -c ./tests/php.ini -s $coverage ./tests/

after_script:
    - >
      if [ "$coverage" != "" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi

 after_failure:
 - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
  directories:
    - $HOME/.composer/cache
