version: '3'
networks:
  bulletpoint:
    external: true

volumes:
  bulletpoint-postgres:
    external: true

services:
    postgres:
      container_name: bulletpoint-postgres
      working_dir: /var/www/bulletpoint/backend
      build: docker/postgres
      env_file: docker/.env.local
      volumes:
        - ./:/var/www/bulletpoint
        - bulletpoint-postgres:/var/lib/postgresql/data
      ports:
        - 5433:5432
      networks:
        - bulletpoint

    redis:
      image: redis:5.0
      container_name: bulletpoint-redis
      working_dir: /var/www/bulletpoint/backend
      networks:
        - bulletpoint

    redis-identity:
      image: redis:5.0
      container_name: bulletpoint-redis-identity
      working_dir: /var/www/bulletpoint/backend
      networks:
        - bulletpoint

    php-fpm:
      build: docker/php-fpm
      working_dir: /var/www/bulletpoint/backend
      volumes:
          - ./:/var/www/bulletpoint
      networks:
        - bulletpoint

    nginx:
      build: docker/nginx
      container_name: bulletpoint-nginx
      working_dir: /var/www/bulletpoint/backend
      volumes:
          - ./:/var/www/bulletpoint:ro
      ports:
        - 80:80
        - 443:443
      networks:
        - bulletpoint

    node:
      build: docker/node
      working_dir: /var/www/bulletpoint/frontend
      command: "sh -c 'yarn && yarn start'"
      volumes:
        - ./:/var/www/bulletpoint
      ports:
        - 3000:3000